"""add actividades tables

Revision ID: 49ce1720b2cb
Revises: 66313a116eb8
Create Date: 2025-10-06 14:48:47.199119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ce1720b2cb'
down_revision: Union[str, None] = '66313a116eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('codact', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomact', sa.String(length=30), nullable=False),
    sa.Column('fechaini', sa.DateTime(), nullable=True),
    sa.Column('fechafin', sa.DateTime(), nullable=True),
    sa.Column('actcerrada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codact')
    )
    op.create_index(op.f('ix_actividades_codact'), 'actividades', ['codact'], unique=False)
    op.create_table('actividades_cerradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codact', sa.String(length=8), nullable=False),
    sa.Column('nomact', sa.String(length=30), nullable=False),
    sa.Column('fechaini', sa.DateTime(), nullable=True),
    sa.Column('fechafin', sa.DateTime(), nullable=True),
    sa.Column('totpers', sa.Integer(), nullable=True),
    sa.Column('totusd', sa.Integer(), nullable=True),
    sa.Column('totmn', sa.Integer(), nullable=True),
    sa.Column('totsm', sa.Integer(), nullable=True),
    sa.Column('elecusd', sa.Integer(), nullable=True),
    sa.Column('elecmn', sa.Integer(), nullable=True),
    sa.Column('salusd', sa.Integer(), nullable=True),
    sa.Column('salmn', sa.Integer(), nullable=True),
    sa.Column('transpusd', sa.Integer(), nullable=True),
    sa.Column('transpmn', sa.Integer(), nullable=True),
    sa.Column('otrosusd', sa.Integer(), nullable=True),
    sa.Column('otrosmn', sa.Integer(), nullable=True),
    sa.Column('porcusd', sa.Integer(), nullable=True),
    sa.Column('pormn', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_cerradas_id'), 'actividades_cerradas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actividades_cerradas_id'), table_name='actividades_cerradas')
    op.drop_table('actividades_cerradas')
    op.drop_index(op.f('ix_actividades_codact'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
