"""initial schema

Revision ID: 527f76daa878
Revises: 
Create Date: 2025-10-14 14:12:05.757714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527f76daa878'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('codact', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomact', sa.String(length=30), nullable=False),
    sa.Column('fechaini', sa.DateTime(), nullable=True),
    sa.Column('fechafin', sa.DateTime(), nullable=True),
    sa.Column('actcerrada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codact')
    )
    op.create_index(op.f('ix_actividades_codact'), 'actividades', ['codact'], unique=False)
    op.create_table('centros_costo',
    sa.Column('cuentacc', sa.String(length=13), nullable=False),
    sa.Column('nomcc', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('cuentacc')
    )
    op.create_table('combinaciones',
    sa.Column('cc', sa.String(length=8), nullable=False),
    sa.Column('cont', sa.String(length=8), nullable=True),
    sa.Column('cl', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('cc')
    )
    op.create_table('contrapartes',
    sa.Column('cuentacont', sa.Integer(), nullable=False),
    sa.Column('nomcont', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('cuentacont')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('monedas',
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('tipos_documentos',
    sa.Column('clave', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("clave ~ '^[A-Z]+$'", name='chk_clave_mayusculas'),
    sa.CheckConstraint('factor IN (-1, 1)', name='chk_factor_valido'),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('um',
    sa.Column('um', sa.String(length=8), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('um')
    )
    op.create_table('actividades_cerradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codact', sa.Integer(), nullable=False),
    sa.Column('nomact', sa.String(length=30), nullable=False),
    sa.Column('fechaini', sa.DateTime(), nullable=True),
    sa.Column('fechafin', sa.DateTime(), nullable=True),
    sa.Column('totpers', sa.Integer(), nullable=True),
    sa.Column('totusd', sa.Integer(), nullable=True),
    sa.Column('totmn', sa.Integer(), nullable=True),
    sa.Column('totsm', sa.Integer(), nullable=True),
    sa.Column('elecusd', sa.Integer(), nullable=True),
    sa.Column('elecmn', sa.Integer(), nullable=True),
    sa.Column('salusd', sa.Integer(), nullable=True),
    sa.Column('salmn', sa.Integer(), nullable=True),
    sa.Column('transpusd', sa.Integer(), nullable=True),
    sa.Column('transpmn', sa.Integer(), nullable=True),
    sa.Column('otrosusd', sa.Integer(), nullable=True),
    sa.Column('otrosmn', sa.Integer(), nullable=True),
    sa.Column('porcusd', sa.Integer(), nullable=True),
    sa.Column('pormn', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['codact'], ['actividades.codact'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_cerradas_id'), 'actividades_cerradas', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('consumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('cantpers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.codact'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_id'), 'consumos', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo_doc_id', sa.String(length=8), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('importe_usd', sa.Integer(), nullable=True),
    sa.Column('importe_mn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tipo_doc_id'], ['tipos_documentos.clave'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_consumos_id'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_actividades_cerradas_id'), table_name='actividades_cerradas')
    op.drop_table('actividades_cerradas')
    op.drop_table('um')
    op.drop_table('tipos_documentos')
    op.drop_table('monedas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('contrapartes')
    op.drop_table('combinaciones')
    op.drop_table('centros_costo')
    op.drop_index(op.f('ix_actividades_codact'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
