"""categoria_id nullable en productos

Revision ID: 66313a116eb8
Revises: 73d55ec88a0c
Create Date: 2025-10-05 20:16:52.827073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66313a116eb8'
down_revision: Union[str, None] = '73d55ec88a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
