"""add descripcion to categoria

Revision ID: 73d55ec88a0c
Revises: 20251005_ajustes_productos_categorias
Create Date: 2025-10-05 19:22:04.765201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d55ec88a0c'
down_revision: Union[str, None] = '20251005_ajustes_productos_categorias'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.drop_constraint('categorias_nombre_key', 'categorias', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categorias_nombre_key', 'categorias', ['nombre'])
    op.drop_column('categorias', 'descripcion')
    # ### end Alembic commands ###
