"""Add audit columns to tipos_documentos

Revision ID: b51a1a56eba0
Revises: 527f76daa878
Create Date: 2025-10-14 21:35:00.241200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51a1a56eba0'
down_revision: Union[str, None] = '527f76daa878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_documentos', sa.Column('creado_en', sa.DateTime(), nullable=True))
    op.add_column('tipos_documentos', sa.Column('desactivado_en', sa.DateTime(), nullable=True))
    op.add_column('tipos_documentos', sa.Column('reactivado_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_documentos', 'reactivado_en')
    op.drop_column('tipos_documentos', 'desactivado_en')
    op.drop_column('tipos_documentos', 'creado_en')
    # ### end Alembic commands ###
